use crate::ast::*;
use crate::hir::types::{DefId, TypeId};
use crate::symbol::Symbol;

#[derive(Debug, Clone, PartialEq)]
pub struct HirProgram<'input> {
    pub items: Vec<HirStmt<'input>>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum HirStmt<'input> {
    VariableDef {
        kind: VariableKind,
        mutable: bool,
        name: Option<Symbol>,
        pattern: Option<HirPattern<'input>>,
        ty: TypeId,
        value: Option<Box<HirExpr<'input>>>,
        else_branch: Option<Vec<HirStmt<'input>>>,
        span: Span,
        type_captures: Vec<TypeParam<'input>>,
    },
    FunctionDef {
        span: Span,
        attributes: Vec<Attribute<'input>>,
        contracts: Vec<Contract<'input>>,
        doc: Option<String>,
        name: Symbol,
        params: Vec<HirParam<'input>>,
        return_type: Option<TypeId>,
        body: Option<Vec<HirStmt<'input>>>,
        type_params: Vec<TypeParam<'input>>,
        where_clause: Option<()>,
        finally: Option<Vec<HirStmt<'input>>>,
        is_comptime: bool,
        is_async: bool,
        is_ieee_contracts: bool,
        hints: Vec<Expr<'input>>,
        /// Whether this function was generated by comptime code
        /// (e.g. from a @comptime_test or a `generate` block).
        /// Used to enforce proof obligations on generated @trusted code.
        generated_by_comptime: bool,
    },
    TypeDef {
        span: Span,
        attributes: Vec<Attribute<'input>>,
        doc: Option<String>,
        name: Symbol,
        params: Vec<TypeParam<'input>>,
        definition: TypeDefinition<'input>,
        contracts: Vec<Contract<'input>>,
    },
    TraitDef {
        span: Span,
        attributes: Vec<Attribute<'input>>,
        doc: Option<String>,
        name: Symbol,
        methods: Vec<TraitMethod<'input>>,
        associated_types: Vec<AssociatedType<'input>>,
    },
    Import {
        path: Vec<Symbol>,
        items: Option<Vec<Symbol>>,
        alias: Option<Symbol>,
        span: Span,
    },
    ExternFunction {
        abi: String,
        name: Symbol,
        params: Vec<HirParam<'input>>,
        return_type: TypeId,
        span: Span,
        attributes: Vec<Attribute<'input>>,
    },
    Constraint {
        name: Symbol,
        bounds: Vec<TypeId>,
        span: Span,
    },
    Edition(String, Span),
    Expression(Box<HirExpr<'input>>),
    If {
        cond: Box<HirExpr<'input>>,
        then_branch: Vec<HirStmt<'input>>,
        else_branch: Option<Vec<HirStmt<'input>>>,
        span: Span,
    },
    IfLet {
        pattern: HirPattern<'input>,
        scrutinee: Box<HirExpr<'input>>,
        then_branch: Vec<HirStmt<'input>>,
        else_branch: Option<Vec<HirStmt<'input>>>,
        span: Span,
    },
    While {
        label: Option<Symbol>,
        cond: Box<HirExpr<'input>>,
        body: Vec<HirStmt<'input>>,
        invariant: Option<Box<HirExpr<'input>>>,
        decreases: Option<Box<HirExpr<'input>>>,
        span: Span,
    },
    WhileLet {
        label: Option<Symbol>,
        pattern: HirPattern<'input>,
        scrutinee: Box<HirExpr<'input>>,
        body: Vec<HirStmt<'input>>,
        invariant: Option<Box<HirExpr<'input>>>,
        decreases: Option<Box<HirExpr<'input>>>,
        span: Span,
    },
    For {
        label: Option<Symbol>,
        pattern: HirPattern<'input>,
        iterable: Box<HirExpr<'input>>,
        body: Vec<HirStmt<'input>>,
        invariant: Option<Box<HirExpr<'input>>>,
        decreases: Option<Box<HirExpr<'input>>>,
        span: Span,
    },
    Loop {
        label: Option<Symbol>,
        body: Vec<HirStmt<'input>>,
        span: Span,
    },
    Leave {
        label: Option<Symbol>,
        span: Span,
    },
    Continue {
        label: Option<Symbol>,
        span: Span,
    },
    Return {
        value: Option<Box<HirExpr<'input>>>,
        /// Path labels attached to this return: `return @label1 @label2 expr`.
        labels: Vec<Symbol>,
        span: Span,
    },
    Assign {
        target: Box<HirExpr<'input>>,
        op: Option<BinOp>,
        value: Box<HirExpr<'input>>,
        span: Span,
    },
    ComptimeBlock {
        /// Variables captured from the enclosing runtime scope via
        /// `comptime [x, y] { ... }`.
        /// Each entry carries the variable name and its source span in
        /// the capture list so that errors can point to the specific name.
        captures: Vec<(Symbol, Span)>,
        /// Whether this block is annotated `@trusted`, granting access to
        /// `@trusted` functions and `unsafe` operations inside comptime.
        trusted: bool,
        body: Vec<HirStmt<'input>>,
        ty: TypeId,
        span: Span,
    },
    ScopeCleanup {
        name: Symbol,
        /// Optional compile-time guard: `scope_cleanup @name when condition { }`
        when_condition: Option<Box<HirExpr<'input>>>,
        body: Vec<HirStmt<'input>>,
        propagates: bool,
        overrides: bool,
        span: Span,
    },
    Trigger {
        name: Symbol,
        span: Span,
    },
    Unsafe {
        body: Vec<HirStmt<'input>>,
        span: Span,
    },
    GhostVariableDef {
        inner: Box<HirStmt<'input>>,
        span: Span,
    },
    Isolate {
        body: Vec<HirStmt<'input>>,
        span: Span,
    },
    LayoutDef {
        name: Symbol,
        attributes: Vec<Attribute<'input>>,
        span: Span,
    },
    ImplBlock {
        span: Span,
        attributes: Vec<Attribute<'input>>,
        trait_path: Option<DefId>,
        for_type: TypeId,
        methods: Vec<ImplMethod<'input>>,
        associated_types: Vec<AssociatedType<'input>>,
    },
    Generate {
        for_type: TypeId,
        body: Vec<HirStmt<'input>>,
        span: Span,
    },
    /// An item that was evaluated and stripped from HIR at compile time
    /// (e.g., a `@comptime_test` function that passed — its body is gone,
    /// but this is not an error).
    Stripped {
        span: Span,
    },
    Error,
}

#[derive(Debug, Clone, PartialEq)]
pub enum HirExpr<'input> {
    Literal(Literal, TypeId, Span),
    Ident(Symbol, TypeId, Span),
    TypeAnnotated {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    BinaryOp {
        left: Box<HirExpr<'input>>,
        op: BinOp,
        right: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    UnaryOp {
        op: UnaryOp,
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    Call {
        callee: Box<HirExpr<'input>>,
        args: Vec<HirExpr<'input>>,
        comptime: bool,
        ty: TypeId,
        span: Span,
    },
    Index {
        base: Box<HirExpr<'input>>,
        index: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    FieldAccess {
        base: Box<HirExpr<'input>>,
        field: Symbol,
        ty: TypeId,
        span: Span,
    },
    AttrAccess {
        base: Box<HirExpr<'input>>,
        attr: Symbol,
        ty: TypeId,
        span: Span,
    },
    Cast {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        safe: bool,
        rounding: Option<Rounding>,
        span: Span,
    },
    Range {
        start: Option<Box<HirExpr<'input>>>,
        end: Option<Box<HirExpr<'input>>>,
        inclusive: bool,
        ty: TypeId,
        span: Span,
    },
    StructLit {
        path: Vec<Symbol>,
        fields: Vec<(Symbol, Box<HirExpr<'input>>)>,
        ty: TypeId,
        span: Span,
    },
    EnumLit {
        path: Vec<Symbol>,
        variant: Symbol,
        payload: Option<Box<HirExpr<'input>>>,
        ty: TypeId,
        span: Span,
    },
    Move(Box<HirExpr<'input>>, TypeId, Span),
    Tuple(Vec<HirExpr<'input>>, TypeId, Span),
    Array(Vec<HirExpr<'input>>, TypeId, Span),
    Closure {
        params: Vec<HirParam<'input>>,
        return_type: TypeId,
        captures: Vec<Capture>,
        body: Vec<HirStmt<'input>>,
        ty: TypeId,
        span: Span,
    },
    Try {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    UnsafeBlock {
        body: Vec<HirStmt<'input>>,
        ty: TypeId,
        span: Span,
    },
    Catch {
        expr: Box<HirExpr<'input>>,
        branches: Vec<HirCatchBranch<'input>>,
        ty: TypeId,
        span: Span,
    },
    LeaveWith {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    /// Success-return terminator (`return expr`).  Kept DISTINCT from
    /// `LeaveWith` (the error exit) — SYNTAX.md requires `leave with` to
    /// retain its distinct identity throughout compilation.
    Return {
        value: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    Await {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    If {
        cond: Box<HirExpr<'input>>,
        then_branch: Vec<HirStmt<'input>>,
        else_branch: Option<Vec<HirStmt<'input>>>,
        is_expression: bool,
        ty: TypeId,
        span: Span,
    },
    IfLet {
        pattern: HirPattern<'input>,
        scrutinee: Box<HirExpr<'input>>,
        then_branch: Vec<HirStmt<'input>>,
        else_branch: Option<Vec<HirStmt<'input>>>,
        ty: TypeId,
        span: Span,
    },
    Match {
        scrutinee: Box<HirExpr<'input>>,
        arms: Vec<HirMatchArm<'input>>,
        ty: TypeId,
        span: Span,
    },
    Block(Vec<HirStmt<'input>>, TypeId, Span),
    PolyBox {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    PolyUnbox {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    Quantified {
        quantifier: crate::ast::Quantifier,
        binder: Symbol,
        range: Box<HirExpr<'input>>,
        body: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    Old {
        expr: Box<HirExpr<'input>>,
        ty: TypeId,
        span: Span,
    },
    Task {
        block: Vec<HirStmt<'input>>,
        ty: TypeId,
        span: Span,
    },
    TypeInfo(TypeId, Span),
    /// Compile-time layout reflection: `layout_of!(Type)`.
    /// Returns a `LayoutDescriptor` describing the type's size, alignment,
    /// and field offsets at comptime.
    /// Compile-time type layout: `layout_of!(Type)!`.
    /// Evaluated at comptime; takes an AST type so that type expressions
    /// (e.g. `layout_of!(typeof(x))`) can be resolved at evaluation time.
    LayoutOf(Box<crate::ast::Type<'input>>, Span),
    /// Compile-time error: `@compile_error!("msg")`.
    /// Produced when the comptime evaluator encounters this expression.
    CompileError(String, Span),
    Error(Span),
}

#[derive(Debug, Clone, PartialEq)]
pub struct HirCatchBranch<'input> {
    pub pattern: HirPattern<'input>,
    pub bind: Option<Symbol>,
    pub body: Vec<HirStmt<'input>>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HirMatchArm<'input> {
    pub pattern: HirPattern<'input>,
    pub guard: Option<Box<HirExpr<'input>>>,
    pub body: Box<HirExpr<'input>>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HirParam<'input> {
    pub name: Symbol,
    pub ty: TypeId,
    pub default: Option<Expr<'input>>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum HirPattern<'input> {
    Wildcard(Span),
    Ident(Symbol, TypeId, Span),
    Literal(Box<HirExpr<'input>>, Span),
    Tuple(Vec<HirPattern<'input>>, Span),
    Struct {
        path: Vec<Symbol>,
        fields: Vec<(Symbol, Box<HirPattern<'input>>)>,
        rest: bool,
        span: Span,
    },
    Enum {
        path: Vec<Symbol>,
        variant: Symbol,
        inner: Option<Box<HirPattern<'input>>>,
        span: Span,
    },
    Or(Vec<HirPattern<'input>>, Span),
    Slice(
        Vec<HirPattern<'input>>,
        Option<Box<HirPattern<'input>>>,
        Vec<HirPattern<'input>>,
        Span,
    ),
    Error(Span),
}

impl<'input> HirExpr<'input> {
    pub fn ty(&self) -> TypeId {
        match self {
            HirExpr::Literal(_, ty, _) => *ty,
            HirExpr::Ident(_, ty, _) => *ty,
            HirExpr::TypeAnnotated { ty, .. } => *ty,
            HirExpr::BinaryOp { ty, .. } => *ty,
            HirExpr::UnaryOp { ty, .. } => *ty,
            HirExpr::Call { ty, .. } => *ty,
            HirExpr::Index { ty, .. } => *ty,
            HirExpr::FieldAccess { ty, .. } => *ty,
            HirExpr::AttrAccess { ty, .. } => *ty,
            HirExpr::Cast { ty, .. } => *ty,
            HirExpr::Range { ty, .. } => *ty,
            HirExpr::StructLit { ty, .. } => *ty,
            HirExpr::EnumLit { ty, .. } => *ty,
            HirExpr::Move(_, ty, _) => *ty,
            HirExpr::Tuple(_, ty, _) => *ty,
            HirExpr::Array(_, ty, _) => *ty,
            HirExpr::Closure { ty, .. } => *ty,
            HirExpr::Try { ty, .. } => *ty,
            HirExpr::UnsafeBlock { ty, .. } => *ty,
            HirExpr::Catch { ty, .. } => *ty,
            HirExpr::LeaveWith { ty, .. } | HirExpr::Return { ty, .. } => *ty,
            HirExpr::Await { ty, .. } => *ty,
            HirExpr::If { ty, .. } => *ty,
            HirExpr::IfLet { ty, .. } => *ty,
            HirExpr::Match { ty, .. } => *ty,
            HirExpr::Block(_, ty, _) => *ty,
            HirExpr::PolyBox { ty, .. } => *ty,
            HirExpr::PolyUnbox { ty, .. } => *ty,
            HirExpr::Quantified { ty, .. } => *ty,
            HirExpr::Old { ty, .. } => *ty,
            HirExpr::Task { ty, .. } => *ty,
            HirExpr::TypeInfo(_, _) => TypeId::NONE,
            HirExpr::LayoutOf(_, _) => TypeId::NONE,
            HirExpr::CompileError(_, _) => TypeId::NONE,
            HirExpr::Error(_) => TypeId::NONE,
        }
    }

    pub fn span(&self) -> Span {
        match self {
            HirExpr::Literal(_, _, span) => *span,
            HirExpr::Ident(_, _, span) => *span,
            HirExpr::TypeAnnotated { span, .. } => *span,
            HirExpr::BinaryOp { span, .. } => *span,
            HirExpr::UnaryOp { span, .. } => *span,
            HirExpr::Call { span, .. } => *span,
            HirExpr::Index { span, .. } => *span,
            HirExpr::FieldAccess { span, .. } => *span,
            HirExpr::AttrAccess { span, .. } => *span,
            HirExpr::Cast { span, .. } => *span,
            HirExpr::Range { span, .. } => *span,
            HirExpr::StructLit { span, .. } => *span,
            HirExpr::EnumLit { span, .. } => *span,
            HirExpr::Move(_, _, span) => *span,
            HirExpr::Tuple(_, _, span) => *span,
            HirExpr::Array(_, _, span) => *span,
            HirExpr::Closure { span, .. } => *span,
            HirExpr::Try { span, .. } => *span,
            HirExpr::UnsafeBlock { span, .. } => *span,
            HirExpr::Catch { span, .. } => *span,
            HirExpr::LeaveWith { span, .. } | HirExpr::Return { span, .. } => *span,
            HirExpr::Await { span, .. } => *span,
            HirExpr::If { span, .. } => *span,
            HirExpr::IfLet { span, .. } => *span,
            HirExpr::Match { span, .. } => *span,
            HirExpr::Block(_, _, span) => *span,
            HirExpr::PolyBox { span, .. } => *span,
            HirExpr::PolyUnbox { span, .. } => *span,
            HirExpr::Quantified { span, .. } => *span,
            HirExpr::Old { span, .. } => *span,
            HirExpr::Task { span, .. } => *span,
            HirExpr::TypeInfo(_, span) => *span,
            HirExpr::LayoutOf(_, span) => *span,
            HirExpr::CompileError(_, span) => *span,
            HirExpr::Error(span) => *span,
        }
    }
}

impl<'input> HirStmt<'input> {
    pub fn span(&self) -> Span {
        match self {
            HirStmt::VariableDef { span, .. } => *span,
            HirStmt::FunctionDef { span, .. } => *span,
            HirStmt::TypeDef { span, .. } => *span,
            HirStmt::TraitDef { span, .. } => *span,
            HirStmt::Import { span, .. } => *span,
            HirStmt::ExternFunction { span, .. } => *span,
            HirStmt::Constraint { span, .. } => *span,
            HirStmt::Edition(_, span) => *span,
            HirStmt::Expression(expr) => expr.span(),
            HirStmt::If { span, .. } => *span,
            HirStmt::IfLet { span, .. } => *span,
            HirStmt::While { span, .. } => *span,
            HirStmt::WhileLet { span, .. } => *span,
            HirStmt::For { span, .. } => *span,
            HirStmt::Loop { span, .. } => *span,
            HirStmt::Leave { span, .. } => *span,
            HirStmt::Continue { span, .. } => *span,
            HirStmt::Return { span, .. } => *span,
            HirStmt::Assign { span, .. } => *span,
            HirStmt::ComptimeBlock { span, .. } => *span,
            HirStmt::ScopeCleanup { span, .. } => *span,
            HirStmt::Trigger { span, .. } => *span,
            HirStmt::Unsafe { span, .. } => *span,
            HirStmt::GhostVariableDef { span, .. } => *span,
            HirStmt::Isolate { span, .. } => *span,
            HirStmt::ImplBlock { span, .. } => *span,
            HirStmt::LayoutDef { span, .. } => *span,
            HirStmt::Generate { span, .. } => *span,
            HirStmt::Stripped { span, .. } => *span,
            HirStmt::Error => Span::new(0, 0),
        }
    }
}
