//! User-friendly token display for diagnostics.

use super::token::Token;

impl Token {
    pub fn to_user_string(&self) -> String {
        match self {
            Token::Ident(s) => format!("`{}`", s.as_str()),
            Token::IntLiteral(s) => match s {
                Ok(n) => format!("the number `{}`", n),
                Err(e) => format!("invalid integer literal: {}", e),
            },
            Token::FloatLiteral(s) => match s {
                Ok(n) => format!("the number `{}`", n),
                Err(e) => format!("invalid float literal: {}", e),
            },
            Token::StringLiteral(s) => match s {
                Ok(s) => format!("the string `\"{}\"`", s),
                Err(e) => format!("invalid string literal: {}", e),
            },
            Token::CharLiteral(s) => match s {
                Ok(c) => format!("the character `'{}'`", *c as char),
                Err(e) => format!("invalid character literal: {}", e),
            },
            Token::ByteStringLiteral(s) => match s {
                Ok(b) => format!("byte string `{:?}`", b),
                Err(e) => format!("invalid byte string literal: {}", e),
            },
            Token::Def => "`def`".to_string(),
            Token::Set => "`set`".to_string(),
            Token::Return => "`return`".to_string(),
            Token::If => "`if`".to_string(),
            Token::Else => "`else`".to_string(),
            Token::For => "`for`".to_string(),
            Token::While => "`while`".to_string(),
            Token::Loop => "`loop`".to_string(),
            Token::Let => "`let`".to_string(),
            Token::Type => "`type`".to_string(),
            Token::Trait => "`trait`".to_string(),
            Token::Impl => "`impl`".to_string(),
            Token::Import => "`import`".to_string(),
            Token::From => "`from`".to_string(),
            Token::Extern => "`extern`".to_string(),
            Token::True => "`true`".to_string(),
            Token::False => "`false`".to_string(),
            Token::Match => "`match`".to_string(),
            Token::And => "`and`".to_string(),
            Token::Or => "`or`".to_string(),
            Token::Not => "`not`".to_string(),
            Token::Mut => "`mut`".to_string(),
            Token::Ref => "`ref`".to_string(),
            Token::Move => "`move`".to_string(),
            Token::Dyn => "`dyn`".to_string(),
            Token::As => "`as`".to_string(),
            Token::Catch => "`catch`".to_string(),
            Token::Panic => "`panic`".to_string(),
            Token::Unsafe => "`unsafe`".to_string(),
            Token::Async => "`async`".to_string(),
            Token::Await => "`await`".to_string(),
            Token::Comptime => "`comptime`".to_string(),
            Token::Leave => "`leave`".to_string(),
            Token::Continue => "`continue`".to_string(),
            Token::Where => "`where`".to_string(),
            Token::Requires => "`requires`".to_string(),
            Token::Ensures => "`ensures`".to_string(),
            Token::Invariant => "`invariant`".to_string(),
            Token::Constraint => "`constraint`".to_string(),
            Token::Generate => "`generate`".to_string(),
            Token::Isolate => "`isolate`".to_string(),
            Token::SelfKw => "`Self`".to_string(),
            // Symbols and operators
            Token::Plus => "`+`".to_string(),
            Token::Minus => "`-`".to_string(),
            Token::Star => "`*`".to_string(),
            Token::Slash => "`/`".to_string(),
            Token::Percent => "`%`".to_string(),
            Token::Ampersand => "`&`".to_string(),
            Token::Pipe => "`|`".to_string(),
            Token::Caret => "`^`".to_string(),
            Token::Tilde => "`~`".to_string(),
            Token::Bang => "`!`".to_string(),
            Token::Question => "`?`".to_string(),
            Token::Dot => "`.`".to_string(),
            Token::DotDot => "`..`".to_string(),
            Token::DotDotEq => "`..=`".to_string(),
            Token::Comma => "`,`".to_string(),
            Token::Semicolon => "`;`".to_string(),
            Token::Colon => "`:`".to_string(),
            Token::ColonColon => "`::`".to_string(),
            Token::Assign => "`=`".to_string(),
            Token::Arrow => "`->`".to_string(),
            Token::FatArrow => "`=>`".to_string(),
            Token::LParen => "`(`".to_string(),
            Token::RParen => "`)`".to_string(),
            Token::LBrace => "`{`".to_string(),
            Token::RBrace => "`}`".to_string(),
            Token::LBracket => "`[`".to_string(),
            Token::RBracket => "`]`".to_string(),
            Token::Lt => "`<`".to_string(),
            Token::Gt => "`>`".to_string(),
            Token::EqEq => "`==`".to_string(),
            Token::Neq => "`!=`".to_string(),
            Token::Le => "`<=`".to_string(),
            Token::Ge => "`>=`".to_string(),
            Token::PlusEq => "`+=`".to_string(),
            Token::MinusEq => "`-=`".to_string(),
            Token::StarEq => "`*=`".to_string(),
            Token::SlashEq => "`/=`".to_string(),
            Token::ShlEq => "`<<=`".to_string(),
            Token::ShrEq => "`>>=`".to_string(),
            Token::Shl => "`<<`".to_string(),
            Token::Shr => "`>>`".to_string(),
            Token::At => "`@`".to_string(),
            // Keywords (continued — first batch at lines ~735–776)
            Token::Default => "`default`".to_string(),
            Token::Copy => "`copy`".to_string(),
            Token::By => "`by`".to_string(),
            Token::In => "`in`".to_string(),
            Token::Auto => "`auto`".to_string(),
            Token::With => "`with`".to_string(),
            Token::When => "`when`".to_string(),
            Token::Const => "`const`".to_string(),
            Token::Finally => "`finally`".to_string(),
            Token::Pub => "`pub`".to_string(),
            Token::Pure => "`pure`".to_string(),
            Token::Io => "`io`".to_string(),
            Token::Linear => "`linear`".to_string(),
            Token::Consume => "`consume`".to_string(),
            Token::Wrap => "`wrap`".to_string(),
            Token::Saturate => "`saturate`".to_string(),
            Token::Trap => "`trap`".to_string(),
            Token::Ieee => "`ieee`".to_string(),
            Token::Old => "`old`".to_string(),
            Token::Ghost => "`ghost`".to_string(),
            Token::ScopeCleanup => "`scope_cleanup`".to_string(),
            Token::Trigger => "`trigger`".to_string(),
            Token::Validate => "`validate`".to_string(),
            Token::Layout => "`layout`".to_string(),
            Token::Alignof => "`alignof`".to_string(),
            Token::Sizeof => "`sizeof`".to_string(),
            Token::Poly => "`poly`".to_string(),
            Token::Unbox => "`unbox`".to_string(),
            Token::Ellipsis => "`...`".to_string(),
            Token::Apostrophe => "`'`".to_string(),
            // Overflow variants
            Token::PlusSaturate => "`+?`".to_string(),
            Token::PlusTrap => "`+!`".to_string(),
            Token::PlusWrap => "`+%`".to_string(),
            Token::MinusSaturate => "`-?`".to_string(),
            Token::MinusTrap => "`-!`".to_string(),
            Token::MinusWrap => "`-%`".to_string(),
            Token::StarSaturate => "`*?`".to_string(),
            Token::StarTrap => "`*!`".to_string(),
            Token::StarWrap => "`*%`".to_string(),
            // Suffix literals
            Token::IntSuffix(_) => "integer with suffix".to_string(),
            Token::BinIntSuffix(_) => "binary integer with suffix".to_string(),
            Token::HexIntSuffix(_) => "hex integer with suffix".to_string(),
            Token::UIntSuffix(_) => "unsigned integer with suffix".to_string(),
            Token::BinUIntSuffix(_) => "binary unsigned integer with suffix".to_string(),
            Token::HexUIntSuffix(_) => "hex unsigned integer with suffix".to_string(),
            Token::BinLiteral(_) => "binary literal".to_string(),
            Token::HexLiteral(_) => "hexadecimal literal".to_string(),
            // Attributes / contracts
            Token::Deprecated => "`deprecated`".to_string(),
            Token::Experimental => "`experimental`".to_string(),
            Token::Endian => "`endian`".to_string(),
            Token::BitOrder => "`bit_order`".to_string(),
            Token::Align => "`align`".to_string(),
            Token::Pad => "`pad`".to_string(),
            Token::Packed => "`packed`".to_string(),
            Token::Decreases => "`decreases`".to_string(),
            Token::Diverges => "`diverges`".to_string(),
            Token::Terminates => "`terminates`".to_string(),
            Token::Exhaustive => "`exhaustive`".to_string(),
            Token::NoAllocError => "`no_alloc_error`".to_string(),
            Token::NoPanic => "`no_panic`".to_string(),
            Token::DebugInfo => "`debug_info`".to_string(),
            Token::IeeeContracts => "`ieee_contracts`".to_string(),
            Token::AuditLog => "`audit_log`".to_string(),
            Token::Interrupt => "`interrupt`".to_string(),
            Token::MustUse => "`must_use`".to_string(),
            Token::MustHandle => "`must_handle`".to_string(),
            Token::MissingMatch => "`missing_match`".to_string(),
            Token::ApplyLemma => "`apply_lemma`".to_string(),
            Token::LinkProof => "`link_proof`".to_string(),
            Token::Propagates => "`propagates`".to_string(),
            Token::Overrides => "`overrides`".to_string(),
            Token::Cfg => "`cfg`".to_string(),
            Token::Hint => "`hint`".to_string(),
            Token::Exists => "`exists`".to_string(),
            Token::Forall => "`forall`".to_string(),
            Token::Implies => "`implies`".to_string(),
            Token::Ceil => "`ceil`".to_string(),
            Token::Floor => "`floor`".to_string(),
            Token::Round => "`round`".to_string(),
            Token::Trunc => "`trunc`".to_string(),
            Token::Task => "`task`".to_string(),
            Token::Channel => "`channel`".to_string(),
            Token::On => "`on`".to_string(),
            Token::OnTimeout => "`on_timeout`".to_string(),
            Token::OnCancel => "`on_cancel`".to_string(),
            Token::NoDefault => "`no_default`".to_string(),
            Token::Edition => "`edition`".to_string(),
            // Tokens that shouldn't appear in user-facing messages
            Token::WhitespaceOrComment => "whitespace or comment".to_string(),
            Token::DocComment(s) => format!("documentation comment `///{}`", s),
            Token::ModuleDocComment(s) => format!("module documentation comment `//!{}`", s),
            Token::Trusted => "`trusted`".to_string(),
            // Fallback for tokens not explicitly listed
            other => format!("{:?}", other),
        }
    }
}
